<?php

declare(strict_types=1);

namespace App\Modules\Catalog\UseCases;

use App\Modules\Catalog\DTOs\CategoryDTO;
use App\Modules\Catalog\Models\Category;
use App\Modules\Catalog\Repositories\CategoryRepository;

/**
 * Admin: renames a category (the slug is regenerated by the model).
 */
final class UpdateCategoryUseCase
{
    public function __construct(private readonly CategoryRepository $categories) {}

    public function execute(Category $category, CategoryDTO $data): Category
    {
        return $this->categories->update($category, $data->toArray())->loadCount('products');
    }
}
